editAreaLoader.lang["hu"]={
new_document: "új üres dokumentum",
search_button: "keresés és csere",
search_command: "keresés tovább / kereső terület megnyitása",
search: "keresés",
replace: "csere",
replace_command: "csere / kereső terület megnyitása",
find_next: "következő keresése",
replace_all: "összes cseréje",
reg_exp: "reguláris kifejezések",
match_case: "kisbetű/nagybetű egyezés",
not_found: "nem található.",
occurrence_replaced: "előfordulás lecserélve.",
search_field_empty: "A kereső mező üres",
restart_search_at_begin: "A terület vége elérve. Kezdés előlről.",
move_popup: "move search popup",
font_size: "--Betűméret--",
go_to_line: "ugrás ebbe a sorba:",
go_to_line_prompt: "ugrás ebbe a sorba:",
undo: "mégse",
redo: "mégis",
change_smooth_selection: "bekapcsol/kikapcsol egyes elemeket (kevesebb megjelenítés, de több CPU használat)",
highlight: "szintaxis kiemelő be/ki",
reset_highlight: "kiemelő nullázás (ha nincs szinkronban a szöveggel)",
help: "névjegy",
save: "ment",
load: "betölt",
line_abbr: "Ln",
char_abbr: "Ch",
position: "Pozíció",
total: "Összes",
close_popup: "ablak bezárás",
shortcuts: "Gyorskapcsok",
add_tab: "tabuláció hozzáadása a szöveghez",
remove_tab: "tabuláció eltávolítása a szövegből",
about_notice: "Megjegyzés: a szintaxis kiemelő csak kis szövegen érvényesül",
toggle: "Szerkesztő váltás",
accesskey: "Gyorsbillentyű",
tab: "Tab",
shift: "Shift",
ctrl: "Ctrl",
esc: "Esc",
processing: "Feldolgozás...",
fullscreen: "teljes képernyő",
syntax_selection: "--Szintaxis--",
syntax_css: "CSS",
syntax_html: "HTML",
syntax_js: "Javascript",
syntax_php: "Php",
syntax_python: "Python",
syntax_vb: "Visual Basic",
syntax_xml: "Xml",
syntax_c: "C",
syntax_cpp: "CPP",
syntax_basic: "Basic",
syntax_pas: "Pascal",
syntax_brainfuck: "Brainfuck",
syntax_sql: "SQL",
syntax_ruby: "Ruby",
close_tab: "Fájl bezárás"
};
